# Generated by Django 3.2.3 on 2021-07-13 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_rename_skills_skill'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='thumbnails',
            new_name='thumbnail',
        ),
        migrations.AlterField(
            model_name='skill',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
